// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bryx_CRM.Data;

#nullable disable

namespace bryx_CRM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130121934_AddIsFavoriteToProduct")]
    partial class AddIsFavoriteToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bryx_CRM.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefective")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Status");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Наушники",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefective = false,
                            IsFavorite = false,
                            Name = "Sony WH-1000XM5",
                            PurchasePrice = 25000m,
                            SalePrice = 29999m,
                            Status = "В наличии",
                            Supplier = "ООО Техносервис"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Наушники",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefective = false,
                            IsFavorite = false,
                            Name = "Apple AirPods Pro",
                            PurchasePrice = 20000m,
                            SalePrice = 24990m,
                            Status = "В наличии",
                            Supplier = "ИП Иванов"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Клавиатуры",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefective = false,
                            IsFavorite = false,
                            Name = "Logitech MX Keys",
                            PurchasePrice = 9000m,
                            SalePrice = 11990m,
                            Status = "В наличии",
                            Supplier = "ООО Техносервис"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Мышки",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefective = false,
                            IsFavorite = false,
                            Name = "Logitech MX Master 3",
                            PurchasePrice = 7000m,
                            SalePrice = 8990m,
                            Status = "В наличии",
                            Supplier = "ИП Петров"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Микрофоны",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefective = false,
                            IsFavorite = false,
                            Name = "Blue Yeti",
                            PurchasePrice = 12000m,
                            SalePrice = 14990m,
                            Status = "Продано",
                            Supplier = "ООО Техносервис"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
